/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d master -i db/Create_Database.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/Tables.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Add_Category_Book.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Create_Author.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Create_Book.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Create_Category.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Delete_Author.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Delete_Book.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Delete_Category.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Delete_Category_Book.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Get_Author_By_Id.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Get_Authors.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Get_Book_By_Id.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Get_Books.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Get_Categories.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Get_Categories_By_Book_Id.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Update_Author.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Update_Book.sql
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P S3cur3P@ssW0rd! -d BOOK_STORE -i db/StoreProcedures/Update_Category.sql